export const cities = [
  { areaName: "Acqui Terme", areaCode: "0144" },
  { areaName: "Adria", areaCode: "0426" },
  { areaName: "Agrigento", areaCode: "0922" },
  { areaName: "Alba", areaCode: "0173" },
  { areaName: "Albenga", areaCode: "0182" },
  { areaName: "Alcamo", areaCode: "0924" },
  { areaName: "Alessandria", areaCode: "0131" },
  { areaName: "Ancona", areaCode: "071" },
  { areaName: "Andria", areaCode: "0883" },
  { areaName: "Aosta", areaCode: "0165" },
  { areaName: "Arezzo", areaCode: "0575" },
  { areaName: "Arona", areaCode: "0322" },
  { areaName: "Ascoli Piceno", areaCode: "0736" },
  { areaName: "Asti", areaCode: "0141" },
  { areaName: "Avellino", areaCode: "0825" },
  { areaName: "Avezzano", areaCode: "0863" },
  { areaName: "Bari", areaCode: "080" },
  { areaName: "Bassano del Grappa", areaCode: "0424" },
  { areaName: "Battipaglia", areaCode: "0828" },
  { areaName: "Baveno", areaCode: "0323" },
  { areaName: "Belluno", areaCode: "0437" },
  { areaName: "Benevento", areaCode: "0824" },
  { areaName: "Bergamo", areaCode: "035" },
  { areaName: "Biella", areaCode: "015" },
  { areaName: "Bologna", areaCode: "051" },
  { areaName: "Bolzano", areaCode: "0471" },
  { areaName: "Borgosesia", areaCode: "0163" },
  { areaName: "Breno", areaCode: "0364" },
  { areaName: "Brescia", areaCode: "030" },
  { areaName: "Bressanone", areaCode: "0472" },
  { areaName: "Brindisi", areaCode: "0831" },
  { areaName: "Brunico", areaCode: "0474" },
  { areaName: "Busto Arsizio", areaCode: "0331" },
  { areaName: "Cagliari", areaCode: "070" },
  { areaName: "Caltagirone", areaCode: "0933" },
  { areaName: "Caltanissetta", areaCode: "0934" },
  { areaName: "Camerino", areaCode: "0737" },
  { areaName: "Campobasso", areaCode: "0874" },
  { areaName: "Casale Monferrato", areaCode: "0142" },
  { areaName: "Casalmaggiore", areaCode: "0375" },
  { areaName: "Caserta", areaCode: "0823" },
  { areaName: "Cassino", areaCode: "0776" },
  { areaName: "Castrovillari", areaCode: "0981" },
  { areaName: "Catania", areaCode: "095" },
  { areaName: "Catanzaro", areaCode: "0961" },
  { areaName: "Cavalese", areaCode: "0462" },
  { areaName: "Cefal\u00f9", areaCode: "0921" },
  { areaName: "Cerignola", areaCode: "0885" },
  { areaName: "Cervignano del Friuli", areaCode: "0431" },
  { areaName: "Cesena", areaCode: "0547" },
  { areaName: "Chianciano Terme", areaCode: "0578" },
  { areaName: "Chiavenna", areaCode: "0343" },
  { areaName: "Chieti", areaCode: "0871" },
  { areaName: "Civitavecchia", areaCode: "0766" },
  { areaName: "Cles", areaCode: "0463" },
  { areaName: "Clusone", areaCode: "0346" },
  { areaName: "Codogno", areaCode: "0377" },
  { areaName: "Comacchio", areaCode: "0533" },
  { areaName: "Como", areaCode: "031" },
  { areaName: "Conegliano", areaCode: "0438" },
  { areaName: "Cortina d'Ampezzo", areaCode: "0436" },
  { areaName: "Cosenza", areaCode: "0984" },
  { areaName: "Crema", areaCode: "0373" },
  { areaName: "Cremona", areaCode: "0372" },
  { areaName: "Crotone", areaCode: "0962" },
  { areaName: "Cuneo", areaCode: "0171" },
  { areaName: "Domodossola", areaCode: "0324" },
  { areaName: "Empoli", areaCode: "0571" },
  { areaName: "Enna", areaCode: "0935" },
  { areaName: "Este", areaCode: "0429" },
  { areaName: "Fabriano", areaCode: "0732" },
  { areaName: "Faenza", areaCode: "0546" },
  { areaName: "Feltre", areaCode: "0439" },
  { areaName: "Fermo", areaCode: "0734" },
  { areaName: "Ferrara", areaCode: "0532" },
  { areaName: "Fidenza", areaCode: "0524" },
  { areaName: "Firenze", areaCode: "055" },
  { areaName: "Foggia", areaCode: "0881" },
  { areaName: "Foligno", areaCode: "0742" },
  { areaName: "Follonica", areaCode: "0566" },
  { areaName: "Forl\u00ec", areaCode: "0543" },
  { areaName: "Formia", areaCode: "0771" },
  { areaName: "Fornovo di Taro", areaCode: "0525" },
  { areaName: "Frosinone", areaCode: "0775" },
  { areaName: "Gallipoli", areaCode: "0833" },
  { areaName: "Genova", areaCode: "010" },
  { areaName: "Gorizia", areaCode: "0481" },
  { areaName: "Grosseto", areaCode: "0564" },
  { areaName: "Iglesias", areaCode: "0781" },
  { areaName: "Imola", areaCode: "0542" },
  { areaName: "Imperia", areaCode: "0183" },
  { areaName: "Isernia", areaCode: "0865" },
  { areaName: "Ivrea", areaCode: "0125" },
  { areaName: "Jesi", areaCode: "0731" },
  { areaName: "L'Aquila", areaCode: "0862" },
  { areaName: "La Spezia", areaCode: "0187" },
  { areaName: "Lagonegro", areaCode: "0973" },
  { areaName: "Lamezia Terme", areaCode: "0968" },
  { areaName: "Lanciano", areaCode: "0872" },
  { areaName: "Lanusei", areaCode: "0782" },
  { areaName: "Lanzo Torinese", areaCode: "0123" },
  { areaName: "Latina", areaCode: "0773" },
  { areaName: "Lecce", areaCode: "0832" },
  { areaName: "Lecco", areaCode: "0341" },
  { areaName: "Legnago", areaCode: "0442" },
  { areaName: "Livorno", areaCode: "0586" },
  { areaName: "Locri", areaCode: "0964" },
  { areaName: "Lodi", areaCode: "0371" },
  { areaName: "Lucca", areaCode: "0583" },
  { areaName: "Lugo", areaCode: "0545" },
  { areaName: "Macerata", areaCode: "0733" },
  { areaName: "Macomer", areaCode: "0785" },
  { areaName: "Maglie", areaCode: "0836" },
  { areaName: "Manfredonia", areaCode: "0884" },
  { areaName: "Mantova", areaCode: "0376" },
  { areaName: "Massa", areaCode: "0585" },
  { areaName: "Matera", areaCode: "0835" },
  { areaName: "Melfi", areaCode: "0972" },
  { areaName: "Menaggio", areaCode: "0344" },
  { areaName: "Merano", areaCode: "0473" },
  { areaName: "Messina", areaCode: "090" },
  { areaName: "Milano", areaCode: "02" },
  { areaName: "Milano", areaCode: "0369" },
  { areaName: "Mirandola", areaCode: "0535" },
  { areaName: "Modena", areaCode: "059" },
  { areaName: "Mondovi'", areaCode: "0174" },
  { areaName: "Montebelluna", areaCode: "0423" },
  { areaName: "Montecatini Terme", areaCode: "0572" },
  { areaName: "Monza", areaCode: "039" },
  { areaName: "Mortara", areaCode: "0384" },
  { areaName: "Muro Lucano", areaCode: "0976" },
  { areaName: "Napoli", areaCode: "081" },
  { areaName: "Novara", areaCode: "0321" },
  { areaName: "Novi Ligure", areaCode: "0143" },
  { areaName: "Nuoro", areaCode: "0784" },
  { areaName: "Olbia", areaCode: "0789" },
  { areaName: "Oristano", areaCode: "0783" },
  { areaName: "Orvieto", areaCode: "0763" },
  { areaName: "Ostiglia", areaCode: "0386" },
  { areaName: "Padova", areaCode: "049" },
  { areaName: "Palermo", areaCode: "091" },
  { areaName: "Palmi", areaCode: "0966" },
  { areaName: "Paola", areaCode: "0982" },
  { areaName: "Parma", areaCode: "0521" },
  { areaName: "Patti", areaCode: "0941" },
  { areaName: "Pavia", areaCode: "0382" },
  { areaName: "Perugia", areaCode: "075" },
  { areaName: "Pesaro", areaCode: "0721" },
  { areaName: "Pescara", areaCode: "085" },
  { areaName: "Piacenza", areaCode: "0523" },
  { areaName: "Pieve di Cadore", areaCode: "0435" },
  { areaName: "Pinerolo", areaCode: "0121" },
  { areaName: "Piombino", areaCode: "0565" },
  { areaName: "Pisa", areaCode: "050" },
  { areaName: "Pistoia", areaCode: "0573" },
  { areaName: "Poggio Mirteto", areaCode: "0765" },
  { areaName: "Pontedera", areaCode: "0587" },
  { areaName: "Pordenone", areaCode: "0434" },
  { areaName: "Porretta Terme", areaCode: "0534" },
  { areaName: "Potenza", areaCode: "0971" },
  { areaName: "Prato", areaCode: "0574" },
  { areaName: "Ragusa", areaCode: "0932" },
  { areaName: "Rapallo", areaCode: "0185" },
  { areaName: "Ravenna", areaCode: "0544" },
  { areaName: "Reggio Calabria", areaCode: "0965" },
  { areaName: "Reggio nell'Emilia", areaCode: "0522" },
  { areaName: "Rieti", areaCode: "0746" },
  { areaName: "Rimini", areaCode: "0541" },
  { areaName: "Rivarolo Canavese", areaCode: "0124" },
  { areaName: "Roma", areaCode: "06" },
  { areaName: "Roma", areaCode: "0769" },
  { areaName: "Rossano", areaCode: "0983" },
  { areaName: "Rovereto", areaCode: "0464" },
  { areaName: "Rovigo", areaCode: "0425" },
  { areaName: "S. Angelo dei Lombardi", areaCode: "0827" },
  { areaName: "S. Benedetto del Tronto", areaCode: "0735" },
  { areaName: "S. Dona' di Piave", areaCode: "0421" },
  { areaName: "S. Marino (Rep. di)", areaCode: "0549" },
  { areaName: "S. Pellegrino Terme", areaCode: "0345" },
  { areaName: "S. Severo", areaCode: "0882" },
  { areaName: "Sala Consilina", areaCode: "0975" },
  { areaName: "Salerno", areaCode: "089" },
  { areaName: "Sal\u00f2", areaCode: "0365" },
  { areaName: "Saluzzo", areaCode: "0175" },
  { areaName: "San remo", areaCode: "0184" },
  { areaName: "Sassari", areaCode: "079" },
  { areaName: "Sassuolo", areaCode: "0536" },
  { areaName: "Savigliano", areaCode: "0172" },
  { areaName: "Savona", areaCode: "019" },
  { areaName: "Scalea", areaCode: "0985" },
  { areaName: "Schio", areaCode: "0445" },
  { areaName: "Sciacca", areaCode: "0925" },
  { areaName: "Seregno", areaCode: "0362" },
  { areaName: "Siena", areaCode: "0577" },
  { areaName: "Siracusa", areaCode: "0931" },
  { areaName: "Sondrio", areaCode: "0342" },
  { areaName: "Soresina", areaCode: "0374" },
  { areaName: "Soverato", areaCode: "0967" },
  { areaName: "Spilimbergo", areaCode: "0427" },
  { areaName: "Spoleto", areaCode: "0743" },
  { areaName: "St. Vincent", areaCode: "0166" },
  { areaName: "Stradella", areaCode: "0385" },
  { areaName: "Sulmona", areaCode: "0864" },
  { areaName: "Susa", areaCode: "0122" },
  { areaName: "Taormina", areaCode: "0942" },
  { areaName: "Taranto", areaCode: "099" },
  { areaName: "Tarvisio", areaCode: "0428" },
  { areaName: "Teramo", areaCode: "0861" },
  { areaName: "Termoli", areaCode: "0875" },
  { areaName: "Terni", areaCode: "0744" },
  { areaName: "Tione di Trento", areaCode: "0465" },
  { areaName: "Tivoli", areaCode: "0774" },
  { areaName: "Tolmezzo", areaCode: "0433" },
  { areaName: "Torino", areaCode: "011" },
  { areaName: "Trapani", areaCode: "0923" },
  { areaName: "Trento", areaCode: "0461" },
  { areaName: "Treviglio", areaCode: "0363" },
  { areaName: "Treviso", areaCode: "0422" },
  { areaName: "Trieste", areaCode: "040" },
  { areaName: "Udine", areaCode: "0432" },
  { areaName: "Urbino", areaCode: "0722" },
  { areaName: "Vallo della Lucania", areaCode: "0974" },
  { areaName: "Varese", areaCode: "0332" },
  { areaName: "Vasto", areaCode: "0873" },
  { areaName: "Venezia (Mestre)", areaCode: "041" },
  { areaName: "Vercelli", areaCode: "0161" },
  { areaName: "Verona", areaCode: "045" },
  { areaName: "Viareggio", areaCode: "0584" },
  { areaName: "Vibo Valentia", areaCode: "0963" },
  { areaName: "Vicenza", areaCode: "0444" },
  { areaName: "Vigevano", areaCode: "0381" },
  { areaName: "Viterbo", areaCode: "0761" },
  { areaName: "Voghera", areaCode: "0383" },
  { areaName: "Volterra", areaCode: "0588" },
  { areaName: "Toll free", areaCode: "800" },
  { areaName: "Vodafone (cellulare)", areaCode: "347" },
  { areaName: "Vodafone (cellulare)", areaCode: "348" },
  { areaName: "Vodafone (cellulare)", areaCode: "349" },
  { areaName: "Operatori virtuali Tim (cellulare)", areaCode: "350" },
  { areaName: "Operatori virtuali Tim (cellulare)", areaCode: "351" },
  { areaName: "Tim (cellulare)", areaCode: "333" },
  { areaName: "Tim (cellulare)", areaCode: "338" },
  { areaName: "Cellular", areaCode: "3" },
];
